baseURL = "https://psbiostats.rbind.io/"
languageCode = "en-us"
title = "Paul Sanfilippo"
theme = "resume"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    firstName = "Paul"
    lastName = "Sanfilippo"
    quals = "M.Biostat,  PhD"
    address = "Melbourne, Australia"
    contactNote = "Biostatistician and Data Scientist"
    profileImage = "img/me_main.jpg"
    email = "prseye@gmail.com"
    description = "Biostatistician and Data Scientist"
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showPublications = true
    showExperience = true
    showEducation = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/paul-sanfilippo-08928516/"
    
[[params.handles]]
    name = "Google Scholar"
    link = "https://scholar.google.com.au/citations?hl=en&user=LBoe_eIAAAAJ&view_op=list_works&sortby=pubdate"  
    
[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/pgseye"    

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/pgseye"

[params.google.analytics]
    trackerID = "UA-128998286-1"
